### ISSUE TITLE
After configure PDO, the Ethercat state mechine cannot switch to OP.

### ISSUE THREAD

**Issue by Jiongyu** [OpenEtherCATsociety/SOEM#300]
Dear sir,
 I am a novice in ethercat.
when I try to run demo "simple_test",the state machine can switch to the op mode.
it generate:
```
SOEM (Simple Open EtherCAT Master)
Simple test
Starting simple test
ec_init on enp4s0 succeeded.
1 slaves found and configured.
Slaves mapped, state to SAFE_OP.
segments : 1 : 20 0 0 0
Request operational state for all slaves
Calculated workcounter 3
Operational state reached for all slaves.
Processdata cycle    1, WKC 3 , O: 00 00 00 00 00 00 00 00 I: 00 00 00 00
Processdata cycle    2, WKC 3 , O: 00 00 00 00 00 00 00 00 I: 00 00 00 00 
Processdata cycle    3, WKC 3 , O: 00 00 00 00 00 00 00 00 I: 00 00 00 00 
.........
```

here is slaveinfo map:
```
SOEM (Simple Open EtherCAT Master)
Slaveinfo
Starting slaveinfo
ec_init on enp4s0 succeeded.
1 slaves found and configured.
Calculated workcounter 3

Slave:1
 Name:? M:0000009a I:00030924
 Output size: 80bits
 Input size: 80bits
 State: 4
 Delay: 0[ns]
 Has DC: 1
 DCParentport:0
 Activeports:1.0.0.0
 Configured address: 1001
 Man: 0000009a ID: 00030924 Rev: 00010420
 SM0 A:1800 L: 140 F:00010026 Type:1
 SM1 A:1900 L: 140 F:00010022 Type:2
 SM2 A:1100 L:  10 F:00010064 Type:3
 SM3 A:1180 L:  10 F:00010020 Type:4
 FMMU0 Ls:00000000 Ll:  10 Lsb:0 Leb:7 Ps:1100 Psb:0 Ty:02 Act:01
 FMMU1 Ls:0000000a Ll:  10 Lsb:0 Leb:7 Ps:1180 Psb:0 Ty:01 Act:01
 FMMUfunc 0:1 1:2 2:0 3:0
 MBX length wr: 140 rd: 140 MBX protocols : 0e
 CoE details: 3f FoE details: 01 EoE details: 01 SoE details: 00
 Ebus current: 0[mA]
 only LRD/LWR:0
PDO mapping according to CoE :
  SM2 outputs
     addr b   index: sub bitl data_type    name
  [0x0000.0] 0x607A:0x00 0x20 INTEGER32    Target position
  [0x0004.0] 0x60FE:0x01 0x20 UNSIGNED32   Physical outputs
  [0x0008.0] 0x6040:0x00 0x10 UNSIGNED16   Controlword
  SM3 inputs
     addr b   index: sub bitl data_type    name
  [0x000A.0] 0x6064:0x00 0x20 INTEGER32    Position actual value
  [0x000E.0] 0x60FD:0x00 0x20 UNSIGNED32   Digital inputs
  [0x0012.0] 0x6041:0x00 0x10 UNSIGNED16   Statusword
End slaveinfo, close socket
End program

```

but I try to map the pdo by sdo,the state machine can not to switch to op mode still in the safe-op mode together with error.

Please let me know what's the cause of this error and how to rectify this.
thank you!!!

wireshark capture:
[cannot_go_to_op.pcapng.txt](https://drive.google.com/uc?authuser=0&id=1cGgWcLZ6hpTXn--5FXGvt0Hed8-z1Zlh&export=download)

[Elmo ECAT DriveGcon_v38_B03.xml](https://drive.google.com/uc?authuser=0&id=1VKE8YTHcbP2i7b6jzU0V2hAvlQ5jKQSi&export=download)

my ethercat init code:

```
bool EtherCatManager::initSoem(const std::string& ifname) {
  // Copy string contents because SOEM library doesn't
  // practice const correctness
  const static unsigned MAX_BUFF_SIZE = 1024;
  char buffer[MAX_BUFF_SIZE];
  size_t name_size = ifname_.size();
  if (name_size > sizeof(buffer) - 1)
  {
    fprintf(stderr, "Ifname %s exceeds maximum size of %u bytes\n", ifname_.c_str(), MAX_BUFF_SIZE);
    return false;
  }
  std::strncpy(buffer, ifname_.c_str(), MAX_BUFF_SIZE);

  printf("Initializing etherCAT master\n");

  if (!ec_init(buffer))
  {
    fprintf(stderr, "Could not initialize ethercat driver\n");
    return false;
  }

  /* find and auto-config slaves */
  if (ec_config_init(FALSE) <= 0)
  {
    fprintf(stderr, "No slaves found on %s\n", ifname_.c_str());
    return false;
  }

  printf("SOEM found and configured %d slaves\n", ec_slavecount);
  for( int cnt = 1 ; cnt <= ec_slavecount ; cnt++)
  {
    // MINAS-A5B Serial Man = 066Fh, ID = [5/D]****[0/4/8][0-F]*
    printf(" Man: %8.8x ID: %8.8x Rev: %8.8x %s\n", (int)ec_slave[cnt].eep_man, (int)ec_slave[cnt].eep_id, (int)ec_slave[cnt].eep_rev, IF_MINAS(ec_slave[cnt])?" MINAS Drivers":"");
    if(IF_MINAS(ec_slave[cnt])) {
      num_clients_++;
    }
  }
  printf("Found %d MINAS Drivers\n", num_clients_);


  if (ec_statecheck(0, EC_STATE_PRE_OP, EC_TIMEOUTSTATE*4) != EC_STATE_PRE_OP)
    {
      fprintf(stderr, "Could not set EC_STATE_PRE_OP\n");
      return false;
    }


  for( int cnt = 1 ; cnt <= ec_slavecount ; cnt++)
    {
      if (! IF_MINAS(ec_slave[cnt])) continue;
      int ret = 0, l;
      uint8_t num_entries;
      l = sizeof(num_entries);
      uint32_t mapping;

      // maximum 64 bits can be mapped to single PDO according to the elmo 301
      /*-------------------------------------RPDO mapping start-----------------------------------------------*/
      ret += ec_SDOread(cnt, 0x1600, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1600, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);

      ret += ec_SDOread(cnt, 0x1601, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1601, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);

      ret += ec_SDOread(cnt, 0x1602, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1602, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      
      ret += ec_SDOread(cnt, 0x1603, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1603, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);

      //  default
      //add control word 6040
      // mapping = 0x6040010;
      // ret += ec_SDOwrite(cnt, 0x1600, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add operation mode 6060
      mapping = 0x6060008;
      ret += ec_SDOwrite(cnt, 0x1600, 0x02, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add target torque 6071
      mapping = 0x6071010;
      ret += ec_SDOwrite(cnt, 0x1600, 0x03, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add max torque 6072
      mapping = 0x6072010;
      ret += ec_SDOwrite(cnt, 0x1601, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add target position 607a
      mapping = 0x607A020;
      ret += ec_SDOwrite(cnt, 0x1601, 0x02, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add max motor speed 6080
      mapping = 0x6080020;
      ret += ec_SDOwrite(cnt, 0x1602, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add Position Offset 60b0
      mapping = 0x60B0020;
      ret += ec_SDOwrite(cnt, 0x1602, 0x02, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

       //add target velocity 60ff
      mapping = 0x60FF0020;
      ret += ec_SDOwrite(cnt, 0x1603, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);     

      // // add position offset (60B0 / 00h / I32)
      // mapping = 0x60B00020;
      // ret += ec_SDOwrite(cnt, 0x1600, 0x09, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);
      // //
      num_entries = 3;
      ret += ec_SDOwrite(cnt, 0x1600, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1600, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);

      num_entries = 2;
      ret += ec_SDOwrite(cnt, 0x1601, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1601, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);

      num_entries = 2;
      ret += ec_SDOwrite(cnt, 0x1602, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1602, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);

      num_entries = 1;
      ret += ec_SDOwrite(cnt, 0x1603, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1603, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      /*-------------------------------------RPDO mapping end-----------------------------------------------*/


      /*-------------------------------------TPDO mapping end-----------------------------------------------*/
      ret += ec_SDOread(cnt, 0x1a00, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1a00, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
     
      ret += ec_SDOread(cnt, 0x1a01, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1a01, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);

      ret += ec_SDOread(cnt, 0x1a02, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);
      printf("len = %d\n", num_entries);
      num_entries = 0;
      ret += ec_SDOwrite(cnt, 0x1a02, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);

      //  default
      //add status word 6041
      // mapping = 0x60410010;
      // ret += ec_SDOwrite(cnt, 0x1a00, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add Error code 603f
      mapping = 0x603F0010;
      ret += ec_SDOwrite(cnt, 0x1a00, 0x02, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add display operation mode 6061
      mapping = 0x6061008;
      ret += ec_SDOwrite(cnt, 0x1a00, 0x03, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add position actual value 6064
      mapping = 0x60640020;
      ret += ec_SDOwrite(cnt, 0x1a01, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add velocity actual value 606c
      mapping = 0x606C0020;
      ret += ec_SDOwrite(cnt, 0x1a01, 0x02, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      //add torque actual value 6077
      mapping = 0x60770010;
      ret += ec_SDOwrite(cnt, 0x1a02, 0x01, FALSE, sizeof(mapping), &mapping, EC_TIMEOUTRXM);

      num_entries = 3;
      l = sizeof(num_entries);
      ret += ec_SDOwrite(cnt, 0x1a00, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1a00, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);

      num_entries = 2;
      l = sizeof(num_entries);
      ret += ec_SDOwrite(cnt, 0x1a01, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1a01, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM);

      num_entries = 1;
      l = sizeof(num_entries);
      ret += ec_SDOwrite(cnt, 0x1a02, 0x00, FALSE, sizeof(num_entries), &num_entries, EC_TIMEOUTRXM);
      ret += ec_SDOread(cnt, 0x1a02, 0x00, FALSE, &l, &num_entries, EC_TIMEOUTRXM); 
      /*-------------------------------------TPDO mapping end-----------------------------------------------*/
      // printf("len = %d\n", num_entries);
    }

  // use PDO mapping 4
  for( int cnt = 1 ; cnt <= ec_slavecount ; cnt++)
    {
      if (! IF_MINAS(ec_slave[cnt])) continue;
      int ret = 0, l;
      uint8_t num_pdo ;
      //uint8_t num_entries;
      // set 0 change PDO mapping index
      num_pdo = 0;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x00, FALSE, sizeof(num_pdo), &num_pdo, EC_TIMEOUTRXM);
      // set to default PDO mapping 1
      uint16_t idx_rxpdo = 0x1600;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x01, FALSE, sizeof(idx_rxpdo), &idx_rxpdo, EC_TIMEOUTRXM);
      idx_rxpdo = 0x1601;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x02, FALSE, sizeof(idx_rxpdo), &idx_rxpdo, EC_TIMEOUTRXM);
      idx_rxpdo = 0x1602;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x03, FALSE, sizeof(idx_rxpdo), &idx_rxpdo, EC_TIMEOUTRXM);
      idx_rxpdo = 0x1603;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x04, FALSE, sizeof(idx_rxpdo), &idx_rxpdo, EC_TIMEOUTRXM);
      // set number of assigned PDOs
      num_pdo = 4;
      ret += ec_SDOwrite(cnt, 0x1c12, 0x00, FALSE, sizeof(num_pdo), &num_pdo, EC_TIMEOUTRXM);
      printf("RxPDO mapping object index %d = %04x ret=%d\n", cnt, idx_rxpdo, ret);

      // set 0 change PDO mapping index
      num_pdo = 0;
      ret += ec_SDOwrite(cnt, 0x1c13, 0x00, FALSE, sizeof(num_pdo), &num_pdo, EC_TIMEOUTRXM);
      // set to default PDO mapping 1
      uint16_t idx_txpdo = 0x1a00;
      ret += ec_SDOwrite(cnt, 0x1c13, 0x01, FALSE, sizeof(idx_txpdo), &idx_txpdo, EC_TIMEOUTRXM);
      idx_txpdo = 0x1a01;
      ret += ec_SDOwrite(cnt, 0x1c13, 0x02, FALSE, sizeof(idx_txpdo), &idx_txpdo, EC_TIMEOUTRXM);
      idx_txpdo = 0x1a02;
      ret += ec_SDOwrite(cnt, 0x1c13, 0x03, FALSE, sizeof(idx_txpdo), &idx_txpdo, EC_TIMEOUTRXM);
      
      // set number of assigned PDOs
      num_pdo = 3;
      ret += ec_SDOwrite(cnt, 0x1c13, 0x00, FALSE, sizeof(num_pdo), &num_pdo, EC_TIMEOUTRXM);
      printf("TxPDO mapping object index %d = %04x ret=%d\n", cnt, idx_txpdo, ret);
    }

  // configure IOMap
  int iomap_size = ec_config_map(iomap_);
  printf("SOEM IOMap size: %d\n", iomap_size);

  ec_slave[0].state = EC_STATE_SAFE_OP;
  ec_send_processdata();
  ec_receive_processdata(EC_TIMEOUTRET);
  ec_writestate( 0 );

  // locates dc slaves
  if(ec_configdc()){
    printf("configure DC success.\n");
  }else{
    printf("configure DC error. \n");
  }

  // '0' here addresses all slaves
  if (ec_statecheck(0, EC_STATE_SAFE_OP, EC_TIMEOUTSTATE*4) != EC_STATE_SAFE_OP)
  {
    fprintf(stderr, "Could not set EC_STATE_SAFE_OP\n");
    return false;
  }

  /*
      This section attempts to bring all slaves to operational status. It does so
      by attempting to set the status of all slaves (ec_slave[0]) to operational,
      then proceeding through 40 send/recieve cycles each waiting up to 50 ms for a
      response about the status.
  */
  ec_slave[0].state = EC_STATE_OPERATIONAL;
  ec_send_processdata();
  ec_receive_processdata(EC_TIMEOUTRET);

  ec_writestate(0);
  int chk = 40;
  do {
    ec_send_processdata();
    ec_receive_processdata(EC_TIMEOUTRET);
    ec_statecheck(0, EC_STATE_OPERATIONAL, 50000); // 50 ms wait for state check
  } while (chk-- && (ec_slave[0].state != EC_STATE_OPERATIONAL));

  if(ec_statecheck(0,EC_STATE_OPERATIONAL, EC_TIMEOUTSTATE) != EC_STATE_OPERATIONAL)
  {
    fprintf(stderr, "OPERATIONAL state not set, exiting\n");
    return false;
  }

  ec_readstate();
  for( int cnt = 1 ; cnt <= ec_slavecount ; cnt++)
    {
      if (! IF_MINAS(ec_slave[cnt])) continue;
      printf("\nSlave:%d\n Name:%s\n Output size: %dbits\n Input size: %dbits\n State: %d\n Delay: %d[ns]\n Has DC: %d\n",
	     cnt, ec_slave[cnt].name, ec_slave[cnt].Obits, ec_slave[cnt].Ibits,
	     ec_slave[cnt].state, ec_slave[cnt].pdelay, ec_slave[cnt].hasdc);
      if (ec_slave[cnt].hasdc) printf(" DCParentport:%d\n", ec_slave[cnt].parentport);
      printf(" Activeports:%d.%d.%d.%d\n", (ec_slave[cnt].activeports & 0x01) > 0 ,
	     (ec_slave[cnt].activeports & 0x02) > 0 ,
	     (ec_slave[cnt].activeports & 0x04) > 0 ,
	     (ec_slave[cnt].activeports & 0x08) > 0 );
      printf(" Configured address: %4.4x\n", ec_slave[cnt].configadr);
    }
  printf("\nFinished configuration successfully\n");
  return true;
}
```

**Comment by ArthurKetels** [comment]
I can not download the Elmo xml. But the wireshark trace shows that the slave does not accept SDO download (is SDOwrite) to objects 16xx and 1axx. Object 1cxx download is fine however. 

Just a guess, but some slave with CompleteAccess CoE functionality do not accept PDO mapping modifications one by one. There you must use CA to change all entries of the object in one go. You could test this.

**Comment by Jiongyu** [comment]
@ArthurKetels , hello , thanks for your time.

there is new elmo xml download:
[Elmo ECAT DriveGcon_v38_B03.xml](https://drive.google.com/uc?authuser=0&id=1VKE8YTHcbP2i7b6jzU0V2hAvlQ5jKQSi&export=download)

there  is elmo cia301:
[elmocia301](https://drive.google.com/uc?authuser=0&id=1_t3fQGrQ2N1-IbxEmniOlaQkttPm8xbz&export=download)

pardon me, what is CA?
how to change all entries of the object in one go?
could you give same example?

thank you.

**Comment by ArthurKetels** [comment]
Thanks for the repost of the ESI file. This file shows that objects 16xx and 1axx are fixed. Meaning that you can not change them. It is possible however to select a number of TxPDO and RxPDO to create your own mapping. Also take into account that some PDO restrict other PDO.

Example from your ESI below. RxPDO 0x1600 can not be changed, is attached to SyncManager 2 and can not be mapped together with RxPDO 0x1601 0x1602 0x1603 0x1604 0x1605 or 0x1606. Tying to do so will result in a fail to go to OP mode.

				<RxPdo Fixed="1" Sm="2">
					<Index>#x1600</Index>
					<Name>Outputs</Name>
					<Exclude>#x1601</Exclude>
					<Exclude>#x1602</Exclude>
					<Exclude>#x1603</Exclude>
					<Exclude>#x1604</Exclude>
					<Exclude>#x1605</Exclude>
					<Exclude>#x1606</Exclude>
					<Entry>
						<Index>#x607A</Index>
						<SubIndex>0</SubIndex>
						<BitLen>32</BitLen>
						<Name>Target Position</Name>
						<DataType>DINT</DataType>
					</Entry>
					<Entry>
						<Index>#x60FE</Index>
						<SubIndex>1</SubIndex>
						<BitLen>32</BitLen>
						<Name>Digital Outputs</Name>
						<DataType>DINT</DataType>
					</Entry>
					<Entry>
						<Index>#x6040</Index>
						<SubIndex>0</SubIndex>
						<BitLen>16</BitLen>
						<Name>Control word</Name>
						<DataType>UINT</DataType>
					</Entry>
				</RxPdo>

**Comment by Jiongyu** [comment]
@ArthurKetels , hello , thank for you help, I try to not change the pdo map and just use the defalut map , but there are still cannot switch to op mode.
there are wireshark file:
[cannot_go_to_op_mode2.pcapng](https://drive.google.com/uc?authuser=0&id=18AH1wMZyk-QdVGoiaZ0LqflV_vudnkQq&export=download)

thank you.

**Comment by ArthurKetels** [comment]
There is nothing wrong this time with the master implementation. The problem is in the slave configuration. But you also made an very very complex mapping. So I would suggest to first try a simple mapping. Just use the factory default and change one thing. Then go from there.

**Comment by Jiongyu** [comment]
@ArthurKetels , I find that 0x1c12 map pdo are exceed 5 and the state machine can not switch to op mode.
after that, the ethercat init success. but I got new error:
`error:channel(224) is larget thatn Input bits (224)`

wireshark:
[error:channel](https://drive.google.com/uc?authuser=0&id=1BeL0gkpAE4pOjNZN52FznHtXXxXxSk7i&export=download)
  thank you.

**Comment by nakarlsson** [comment]
still an issue?

**Comment by nakarlsson** [comment]
@Jiongyu , can we close this issue?
